default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: containerized_blog_development
  username: cpcwood
  password: password
  port: 5432

test:
  <<: *default
  database: containerized_blog_test
  username: cpcwood
  password: password

production:
  <<: *default
  database: containerized_blog_production
  username: cpcwood
  password: password
