default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  port: 5432

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { 'containerized_blog_development' } %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { 'containerized_blog_test' } %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { 'containerized_blog_production' } %>
